"""Tests for skills/hep-analysis/scripts/systematics_table_tex.py (T26): a booktabs table from the systematics registry
that always carries its status label, escapes LaTeX, and refuses an unlabeled or malformed table."""
import contextlib
import io
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SCRIPT = ROOT / "skills" / "hep-analysis" / "scripts" / "systematics_table_tex.py"
ASSET = ROOT / "skills" / "hep-analysis" / "assets" / "systematics.csv"
sys.path.insert(0, str(SCRIPT.parent))
import systematics_table_tex as st  # noqa: E402


def run(*argv):
    out, err = io.StringIO(), io.StringIO()
    with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
        code = st.main(list(argv))
    return code, out.getvalue(), err.getvalue()


class SystematicsTableTests(unittest.TestCase):
    def test_the_shipped_registry_with_a_status(self):
        code, tex, _ = run("--input", str(ASSET), "--status", "synthetic")
        self.assertEqual(code, 0)
        self.assertIn("% generated by systematics_table_tex.py; status: synthetic", tex)
        self.assertIn(r"\caption{SYNTHETIC: Sources", tex)
        for cmd in (r"\toprule", r"\midrule", r"\bottomrule", r"\begin{tabular}{llllll}"):
            self.assertIn(cmd, tex)
        self.assertIn(r"example\_detector & template & simulation", tex)  # underscores escaped
        self.assertEqual(tex.count(r" \\"), 3)  # header and two rows

    def test_observed_is_labelled_in_the_comment_not_flagged_in_the_caption(self):
        code, tex, _ = run("--input", str(ASSET), "--status", "observed", "--caption", "Systematics & 100% of it")
        self.assertEqual(code, 0)
        self.assertIn("status: observed", tex)
        self.assertIn(r"\caption{Systematics \& 100\% of it}", tex)

    def test_per_row_status_and_impact_columns(self):
        with tempfile.TemporaryDirectory() as td:
            p = Path(td) / "s.csv"
            p.write_text("source,type,impact_percent,status\njes,shape,2.1,observed\nlumi,norm,1.6,preliminary\n")
            code, tex, _ = run("--input", str(p), "--columns", "source,impact_percent")
        self.assertEqual(code, 0)
        self.assertIn(r"\caption{PRELIMINARY: ", tex)
        self.assertIn(r"Source & Impact percent & Status \\", tex)
        self.assertIn(r"jes & 2.1 & observed \\", tex)

    def test_refusals(self):
        with tempfile.TemporaryDirectory() as td:
            nostatus = Path(td) / "a.csv"
            nostatus.write_text("source,type\nx,y\n")
            badstatus = Path(td) / "b.csv"
            badstatus.write_text("source,status\nx,final\n")
            empty = Path(td) / "c.csv"
            empty.write_text("source,type\n")
            for argv, needle in (([str(nostatus)], "no status"), ([str(badstatus)], "is not one of"),
                                 ([str(empty), "--status", "observed"], "no rows"),
                                 ([str(nostatus), "--status", "observed", "--columns", "source,nope"], "not in the CSV"),
                                 (["/nonexistent/s.csv", "--status", "observed"], "No such file")):
                code, out, err = run("--input", *argv)
                self.assertEqual(code, 2, argv)
                self.assertIn(needle, err)
                self.assertEqual(out, "")

    @unittest.skipUnless(shutil.which("pdflatex"), "pdflatex not installed: the table was not compiled")
    def test_compiles_with_booktabs(self):
        with tempfile.TemporaryDirectory() as td:
            table = Path(td) / "t.tex"
            self.assertEqual(run("--input", str(ASSET), "--status", "synthetic", "--out", str(table))[0], 0)
            (Path(td) / "doc.tex").write_text("\\documentclass{article}\\usepackage{booktabs}\\begin{document}"
                                              "\\input{t.tex}\\end{document}\n")
            res = subprocess.run(["pdflatex", "-interaction=nonstopmode", "doc.tex"], cwd=td, capture_output=True,
                                 text=True, timeout=120)
            self.assertEqual(res.returncode, 0, res.stdout[-1500:])


if __name__ == "__main__":
    unittest.main()
