#!/usr/bin/env python3
"""Path D (journey J5): compare the tree-level QED prediction (Path C) with SYNTHETIC reconstructed data from the
illustrative synthetic-collider profile (Path B) and fit a normalization scale mu.

SYNTHETIC. The data are generated by the synthetic-collider generator with sigma_gen = mu_inj x sigma_pred, where
sigma_pred comes from the Path C prediction artifact; this harness injects that number through the generator's
sigma argument (the profile itself imports no theory code). mu = 1 is the truth for the main sample. Nothing here
is a physics result, and no "new physics" statement is possible or made.

Chain (contract trace): Path C prediction artifact -> composition diagnostics (both profiles) -> comparison gate
(declared transformations: bin-integrate, multiply by integrated luminosity, forward-fold through the synthetic
response) -> folded expectation in reconstructed cos theta bins -> Poisson likelihood with a Gaussian luminosity
constraint and a bounded (flat) nuisance for the rounding of the theory reference constant -> profile-likelihood
fit of mu -> Asimov injection at mu = 1 and mu != 1, seeded toys (coverage, pulls) -> mismatched variants that the
gate must reject -> contract artifacts, figure, report.

Usage (from the plugin root): python3 examples/theory-comparison/run.py [--toys 200] [--seed 20261004] [--out DIR]
Run examples/qed-prediction/run.py first if its output is missing. Exit 0 when every pre-declared criterion
passes, 1 otherwise. Requires numpy, scipy and matplotlib (D5 environment).
"""
from __future__ import annotations

import argparse
import copy
import hashlib
import json
import math
import sys
from pathlib import Path

import numpy as np
from scipy import integrate, optimize, special

PLUGIN = Path(__file__).resolve().parents[2]
EXP_DIR = PLUGIN / "profiles" / "experiments" / "synthetic-collider"
TH_DIR = PLUGIN / "profiles" / "theory" / "qed-benchmark"
PRED_PATH = PLUGIN / "examples" / "qed-prediction" / "output" / "artifacts" / "prediction.json"
PATH_B_RESPONSE = PLUGIN / "examples" / "collider-angular" / "output" / "artifacts" / "response.json"
PATH_B_RESULTS = PLUGIN / "examples" / "collider-angular" / "output" / "results.json"
sys.path.insert(0, str(PLUGIN))
sys.path.insert(0, str(EXP_DIR / "scripts"))
import detector  # noqa: E402
import generate_events  # noqa: E402
from contracts import CONTRACTS_VERSION  # noqa: E402
from contracts.comparison.composition import compose  # noqa: E402
from contracts.comparison.gate import gate, side_from_artifact  # noqa: E402
from contracts.validate import validate_artifact  # noqa: E402
from contracts.vocab import Vocabulary  # noqa: E402

EXP = json.loads((EXP_DIR / "profile.json").read_text(encoding="utf-8"))
TH = json.loads((TH_DIR / "profile.json").read_text(encoding="utf-8"))
EXP_CONV = json.loads((EXP_DIR / "conventions.json").read_text(encoding="utf-8"))
CFG = json.loads((EXP_DIR / "benchmarks" / "path-b.json").read_text(encoding="utf-8"))
PLUGIN_VERSION = json.loads((PLUGIN / ".claude-plugin" / "plugin.json").read_text(encoding="utf-8"))["version"]

TE, RE = np.array(CFG["truth_edges"]), np.array(CFG["reco_edges"])
LUMI, LUMI_REL = CFG["integrated_luminosity_pb"], CFG["luminosity_rel_uncertainty"]
MU_INJECT = (1.0, 0.8)
CRITERIA = {"fold_vs_quadrature_max_rel_dev": 1e-6, "asimov_mu_abs_dev": 1e-8, "observed_pull_abs": 3.0,
            "toy_mean_pull_abs": 0.2, "toy_pull_width": (0.85, 1.15), "coverage_sigma": 3.0}


# --- the comparison plan ---------------------------------------------------------------------------------------

def measurement_observable() -> dict:
    return {"quantity": "event-count", "process": "e+e- -> mu+mu- (synthetic generator)",
            "variables": [{"name": "cos_theta", "unit": "1", "edges": RE.tolist()}],
            "phase_space": {"definition": "SYNTHETIC: all selected events with reconstructed cos theta in [-1, 1]", "fiducial": False},
            "level": "detector", "frame": "center-of-mass",
            "normalization": {"kind": "integrated-luminosity", "value": LUMI, "unit": "pb^-1",
                              "convention": "expected counts = integrated luminosity x folded bin-integrated cross section"},
            "bin_semantics": "bin-integrated", "unit": "1",
            "conventions": {"energy_variable": EXP_CONV["energy_variable"], "angle_definition": EXP_CONV["angle_definition"]}}


def plan(response_includes) -> dict:
    return {
        "transformations": [
            {"kind": "bin-integrate", "owner": "hep-theory", "note": "bin-averaged d sigma / d cos theta x bin width"},
            {"kind": "multiply-by-normalization", "owner": "hep-statistics", "normalization_kind": "integrated-luminosity",
             "value": LUMI, "value_unit": "pb^-1", "unit_in": "pb", "unit_out": "1"},
            {"kind": "forward-fold", "owner": "hep-statistics", "truth_edges": TE.tolist(), "reco_edges": RE.tolist(),
             "truth_level": "parton", "includes": list(response_includes),
             "justification": "the synthetic generator has no QED radiation, so its truth muons are the hard-process leptons; "
                              "the response is built with the in-bin weighting 1 + cos^2 theta, the predicted shape"}],
        "mappings": [{"key": "angle_definition", "action": "equivalent",
                      "justification": "both define theta as the angle between the incoming e- (beam) and the outgoing mu- in the "
                                       "c.m. frame; the wording differs only"},
                     {"field": "process", "action": "equivalent",
                      "justification": "the synthetic generator samples the same one-photon tree-level e+e- -> mu+mu- matrix element "
                                       "(no Z, no radiation) that the prediction computes"},
                     {"field": "phase_space", "action": "equivalent",
                      "justification": "the prediction covers the full truth range cos theta in [-1, 1]; the response maps it to "
                                       "the reco range [-1, 1] and carries the selection efficiency, so the folded prediction "
                                       "describes the selected events"}],
        "measurement_conditions": {"sqrt_s_gev": CFG["sqrt_s_gev"]},
    }


def negative_variants(pred_side: dict, meas_side: dict, base_plan: dict, unfolded_side: dict) -> list[dict]:
    """Mismatched comparisons the gate must reject; each names the field expected in the mismatch list."""
    out = []

    def add(name, field, p=None, m=None, transformations=None, mappings=None, conditions=None):
        out.append({"name": name, "expect_field": field, "prediction": p or pred_side, "measurement": m or meas_side,
                    "transformations": base_plan["transformations"] if transformations is None else transformations,
                    "mappings": base_plan["mappings"] if mappings is None else mappings,
                    "conditions": base_plan["measurement_conditions"] if conditions is None else conditions})

    p = copy.deepcopy(pred_side); p["parameter_point"] = {"sqrt_s_gev": 91.2}
    add("prediction at a different sqrt(s)", "parameter_point.sqrt_s_gev", p=p)
    p = copy.deepcopy(pred_side); p["observable"]["unit"] = "nb"
    add("prediction in nb without a unit conversion", "transformations[1]", p=p)
    p = copy.deepcopy(pred_side); p["observable"]["variables"][0]["edges"] = [-1.0, -0.5, 0.0, 0.5, 1.0]
    add("prediction bins differ from the response truth bins", "transformations[2]", p=p)
    p = copy.deepcopy(pred_side); p["observable"]["bin_semantics"] = "point"
    add("point values compared with bins without a mapping", "transformations[0]", p=p)
    t = copy.deepcopy(base_plan["transformations"])
    t.insert(2, {"kind": "apply-correction", "owner": "hep-statistics", "effect": "efficiency",
                 "justification": "deliberate double counting for the negative test"})
    add("efficiency applied before folding with a response that includes it", "transformations[3]",
        p=dict(copy.deepcopy(pred_side), allowed_transformations=None), transformations=t)
    add("angle definitions without a declared mapping", "conventions.angle_definition",
        mappings=[m for m in base_plan["mappings"] if m.get("key") != "angle_definition"])
    add("process definitions without a declared mapping", "process",
        mappings=[m for m in base_plan["mappings"] if m.get("field") != "process"])
    m = copy.deepcopy(meas_side); m["observable"]["normalization"]["kind"] = "exposure"
    add("measurement normalized to exposure", "normalization.kind", m=m)
    add("folded prediction against the unfolded (Path B) result", "level", m=unfolded_side)
    add("inclusive prediction against the fiducial unfolded result", "phase_space.fiducial", m=unfolded_side, transformations=[],
        mappings=base_plan["mappings"] + [{"key": "synthcol:fiducial_definition", "action": "irrelevant",
                                           "justification": "negative test: the fiducial check itself must still fail"}])
    return out


def positive_conversion(pred_side, unfolded_side, base_plan) -> dict:
    """T08: documented conversion to the unfolded fiducial result (restrict to |cos theta| < 0.9, identify levels)."""
    t = [{"kind": "level-identification", "owner": "hep-theory", "from": "parton", "to": "particle-fiducial",
          "justification": "tree level without radiation: the outgoing muon is the stable final-state particle"},
         {"kind": "fiducial-restriction", "owner": "hep-theory", "variable": "cos_theta", "range": [-0.9, 0.9]}]
    maps = [m for m in base_plan["mappings"] if m.get("field") != "phase_space"] + [
        {"field": "phase_space", "action": "equivalent",
         "justification": "after the restriction to |cos theta| < 0.9 the prediction covers the unfolded result's fiducial region"},
        {"key": "synthcol:fiducial_definition", "action": "transform",
                                     "transformation": "fiducial-restriction to |cos theta| < 0.9",
                                     "justification": "the cut is on the binned variable and edges align at +-0.9"}]
    return gate(pred_side, unfolded_side, t, maps, base_plan["measurement_conditions"])


# --- numerics ----------------------------------------------------------------------------------------------------

def folded(pred_doc, resp_matrix):
    v = pred_doc["extension"]["values"]
    width = np.diff(np.array(v["edges"]))
    sigma_bins = np.array(v["values"]) * width          # bin-integrate: pb per truth bin
    return sigma_bins, resp_matrix @ (LUMI * sigma_bins)  # forward-fold expected counts


def quadrature_reference(sigma_total):
    """Independent expected counts per reco bin: integrate L x (3/8) sigma (1 + c^2) x eff(c) x P(reco in bin | c)."""
    e0, e1, s = CFG["efficiency"]["e0"], CFG["efficiency"]["e1"], CFG["resolution"]["sigma_cos"]
    out = []
    for lo, hi in zip(RE[:-1], RE[1:]):
        f = lambda c, lo=lo, hi=hi: LUMI * 0.375 * sigma_total * (1 + c * c) * (e0 - e1 * c ** 4) * (  # noqa: E731
            special.ndtr((hi - c) / s) - special.ndtr((lo - c) / s))
        out.append(integrate.quad(f, -1.0, 1.0, epsabs=0, epsrel=1e-12, limit=200, points=[lo, hi])[0])
    return np.array(out)


class Model:
    """n_k ~ Poisson(mu x kappa x (1 + d theta) x A_k), theta ~ N(0, 1), kappa flat in [1 - r, 1 + r]."""

    def __init__(self, counts, a, d, r, constrain=True):
        self.n, self.a, self.d, self.r, self.constrain = np.asarray(counts, float), np.asarray(a, float), d, r, constrain

    def nll(self, mu, theta, kappa):
        nu = mu * kappa * (1 + self.d * theta) * self.a
        if np.any(nu <= 0):
            return 1e300
        pos = self.n > 0
        val = float(np.sum(nu) - np.sum(self.n[pos] * np.log(nu[pos])))
        return val + (0.5 * theta * theta if self.constrain else 0.0)

    def profiled(self, mu):
        best = None
        for k0 in (1.0, 1 - self.r, 1 + self.r):
            res = optimize.minimize(lambda x: self.nll(mu, x[0], x[1]), x0=[0.0, k0], method="L-BFGS-B",
                                    bounds=[(-10.0, 10.0), (1 - self.r, 1 + self.r)], options={"ftol": 1e-15, "gtol": 1e-12})
            if best is None or res.fun < best.fun:
                best = res
        return best.fun, best

    def fit(self):
        s_hat = float(self.n.sum() / self.a.sum())  # mu x kappa x (1 + d theta) is all the counts identify
        nll0, _ = self.profiled(s_hat)
        q = lambda mu: 2.0 * (self.profiled(mu)[0] - nll0)  # noqa: E731
        guess = s_hat * math.sqrt(1.0 / max(self.n.sum(), 1.0) + self.d ** 2 + self.r ** 2)
        lo = optimize.brentq(lambda m: q(m) - 1.0, s_hat * 0.2, s_hat - 1e-3 * guess, xtol=1e-10)
        hi = optimize.brentq(lambda m: q(m) - 1.0, s_hat + 1e-3 * guess, s_hat * 3.0, xtol=1e-10)
        return {"mu_hat": s_hat, "interval_68": [lo, hi], "sigma_minus": s_hat - lo, "sigma_plus": hi - s_hat,
                "plateau": [s_hat / (1 + self.r), s_hat / (1 - self.r)], "q": q}


def reco_counts(ev):
    sel = ev["selected"] & (ev["reco_cos"] >= RE[0]) & (ev["reco_cos"] < RE[-1])
    return np.histogram(ev["reco_cos"][sel], bins=RE)[0].astype(float)


def toys(fold_counts, sigma_total, r, n_toys, seed):
    out = {}
    for mu_inj in MU_INJECT:
        rng = np.random.default_rng(seed + int(round(mu_inj * 1000)))
        pulls, cover = [], 0
        for i in range(n_toys):
            ev = generate_events.generate(CFG, int(rng.integers(2 ** 31)), sigma_pb=mu_inj * sigma_total, a=1.0, b=0.0)
            lumi_obs = LUMI * (1.0 + LUMI_REL * rng.normal())  # auxiliary luminosity measurement
            fit = Model(reco_counts(ev), fold_counts * lumi_obs / LUMI, LUMI_REL, r).fit()
            lo, hi = fit["interval_68"]
            cover += lo <= mu_inj <= hi
            sig = fit["sigma_plus"] if fit["mu_hat"] < mu_inj else fit["sigma_minus"]
            pulls.append((mu_inj - fit["mu_hat"]) / sig)
        p = np.array(pulls)
        out[f"{mu_inj:g}"] = {"toys": n_toys, "mean_pull": round(float(p.mean()), 4), "pull_width": round(float(p.std(ddof=1)), 4),
                              "coverage_68": round(cover / n_toys, 4)}
    return out


# --- artifacts ---------------------------------------------------------------------------------------------------

def artifacts(pred_doc, gate_res, fold_counts, r, counts, obs_fit, toy_res, created):
    vocab = Vocabulary.with_profiles([EXP, TH])
    base = {"contract_version": CONTRACTS_VERSION,
            "bindings": {"experiments": [{"profile": EXP["id"], "version": EXP["version"]}],
                         "theory": [{"profile": TH["id"], "version": TH["version"]}]},
            "versions": {"plugin": PLUGIN_VERSION, "contracts": CONTRACTS_VERSION,
                         "profiles": {EXP["id"]: EXP["version"], TH["id"]: TH["version"]}},
            "outputs": [], "unresolved_inputs": []}
    pred_in = {"ref": "../qed-prediction/output/artifacts/prediction.json", "artifact_type": "prediction", "status": pred_doc["status"]}
    resp_in = {"ref": "../collider-angular/output/artifacts/response.json", "artifact_type": "response", "status": ["synthetic"]}
    data_in = {"ref": "artifacts/dataset_record.json", "artifact_type": "dataset-record", "status": ["synthetic"]}
    obs = measurement_observable()
    data = dict(base, artifact_id="synthetic-path-d-reco-counts", artifact_type="dataset-record", inputs=[],
                objective="SYNTHETIC reconstructed cos theta counts generated at mu = 1 (sigma_gen = sigma_pred)",
                provenance={"producer_skill": "hep-analysis", "created": created}, status=["synthetic"],
                extension={"dataset_id": "synthcol:synthetic-path-d-reco-counts", "source_evidence_ids": [], "observable": obs,
                           "data": {"edges": RE.tolist(), "values": counts.tolist(), "unit": "1",
                                    "uncertainties": [{"name": "Poisson counts", "kind": "statistical", "correlation": "uncorrelated"}]},
                           "covariance": {"status": "absent", "note": "Poisson counts: the likelihood carries the statistical model"},
                           "period": "not-applicable", "status": "synthetic", "experiment_profile": EXP["id"],
                           "conditions": f"sqrt_s_gev = {CFG['sqrt_s_gev']}"})
    comp = dict(base, artifact_id="synthetic-path-d-comparison", artifact_type="comparison-spec", inputs=[pred_in, data_in, resp_in],
                objective="Gate and plan: QED prediction vs SYNTHETIC reconstructed counts",
                provenance={"producer_skill": "hep-statistics", "created": created}, status=["synthetic"],
                extension={"dataset_bindings": ["synthcol:synthetic-path-d-reco-counts"], "prediction_bindings": [pred_doc["artifact_id"]],
                           "gate_result": {"comparable": gate_res["comparable"], "mismatches": gate_res["mismatches"],
                                           "notes": gate_res["notes"]},
                           "transformations": [{k: v for k, v in t.items() if k not in ("before", "after")} for t in gate_res["transformations"]],
                           "correlations": [{"between": ["luminosity", "all reco bins"], "kind": "fully correlated normalization"},
                                            {"between": ["reference-constant rounding", "all bins"], "kind": "fully correlated, bounded"}],
                           "inference_assumptions": [
                               "luminosity uncertainty Gaussian with the synthetic 2% width (declared in the profile benchmark)",
                               "reference-constant rounding is a bounded flat interval, not Gaussianized",
                               "truncation (higher orders, Z exchange) is not quantified: mu is conditional on the tree-level prediction"],
                           "limits": ["synthetic data; mu = 1 is the generated truth", "no statement about physics beyond the benchmark"]})
    fold = dict(base, artifact_id="synthetic-path-d-folded-expectation", artifact_type="prediction", inputs=[pred_in, resp_in],
                objective="QED prediction folded to reconstructed cos theta counts at mu = 1",
                provenance={"producer_skill": "hep-statistics", "created": created}, status=["synthetic"],
                extension={"observable": dict(obs, process="e+e- -> mu+mu- (tree-level QED, folded)"),
                           "parameter_point": {"sqrt_s_gev": CFG["sqrt_s_gev"], "mu": 1.0}, "representation": "numerical",
                           "values": {"edges": RE.tolist(), "values": fold_counts.tolist(), "unit": "1",
                                      "uncertainties": [{"name": "reference rounding", "kind": "parametric",
                                                         "values": (fold_counts * r).tolist(), "correlation": "fully-correlated"}]},
                           "uncertainties": [{"name": "missing higher orders and Z exchange", "kind": "truncation", "correlation": "unknown"}],
                           "allowed_transformations": []})
    stat = dict(base, artifact_id="synthetic-path-d-mu-fit", artifact_type="statistical-result",
                inputs=[{"ref": "artifacts/comparison_spec.json", "artifact_type": "comparison-spec", "status": ["synthetic"]},
                        {"ref": "artifacts/folded_expectation.json", "artifact_type": "prediction", "status": ["synthetic"]}, data_in],
                objective="Normalization scale mu of the QED prediction on SYNTHETIC data",
                provenance={"producer_skill": "hep-statistics", "created": created}, status=["synthetic"],
                extension={"paradigm": "frequentist",
                           "likelihood": {"form": "product of Poisson terms over reconstructed bins x Gaussian luminosity constraint",
                                          "expected": "mu x kappa x (1 + 0.02 theta) x L_obs x (R sigma)_k"},
                           "parameters_of_interest": ["mu"],
                           "nuisances": ["theta (luminosity, Gaussian constraint)", "kappa (reference rounding, flat in +-%.1e)" % r],
                           "constraints": [{"parameter": "theta", "form": "normal(0, 1)"},
                                           {"parameter": "kappa", "form": f"uniform[{1 - r:.6f}, {1 + r:.6f}]"}],
                           "test_statistic": "profile likelihood ratio q(mu) = 2 [NLL(mu, profiled) - NLL_min]",
                           "construction": "profile-likelihood-wilks",
                           "coverage": {"method": "seeded toys from the synthetic generator with a fluctuated luminosity measurement",
                                        "result": toy_res},
                           "fit_status": "converged",
                           "results": {"mu_hat": obs_fit["mu_hat"], "interval_68": obs_fit["interval_68"], "plateau_from_kappa": obs_fit["plateau"]}})
    docs = {"dataset_record": data, "comparison_spec": comp, "folded_expectation": fold, "result": stat}
    return docs, {k: {"ok": (rp := validate_artifact(v, vocab)).ok, "errors": [f.message for f in rp.errors]} for k, v in docs.items()}


def figures(counts, fold_counts, obs_fit, lumi_obs, out):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    c = 0.5 * (RE[1:] + RE[:-1])
    fig, (ax, bx) = plt.subplots(1, 2, figsize=(10, 4))
    ax.errorbar(c, counts, yerr=np.sqrt(counts), xerr=np.diff(RE) / 2, fmt="o", ms=4, label="SYNTHETIC reco counts (mu = 1 injected)")
    ax.stairs(fold_counts, RE, baseline=None, label="QED prediction folded, mu = 1")
    ax.stairs(fold_counts * obs_fit["mu_hat"] * lumi_obs / LUMI, RE, baseline=None, ls="--",
              label=f"fitted mu = {obs_fit['mu_hat']:.3f} (measured luminosity)")
    ax.set_xlabel("reconstructed cos theta"); ax.set_ylabel("events per bin"); ax.set_ylim(bottom=0)
    ax.set_title("SYNTHETIC Path D"); ax.legend(fontsize=7)
    lo, hi = obs_fit["interval_68"]
    grid = np.linspace(lo - 1.5 * (obs_fit["mu_hat"] - lo), hi + 1.5 * (hi - obs_fit["mu_hat"]), 61)
    bx.plot(grid, [obs_fit["q"](m) for m in grid])
    bx.axhline(1.0, ls=":", c="gray"); bx.set_xlabel("mu"); bx.set_ylabel("q(mu)"); bx.set_title("profile likelihood (synthetic)")
    fig.tight_layout(); fig.savefig(out / "folded_comparison.png", dpi=110); plt.close(fig)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--toys", type=int, default=200)
    ap.add_argument("--seed", type=int, default=20261004)
    ap.add_argument("--created", default="2026-10-02")
    ap.add_argument("--out", type=Path, default=Path(__file__).resolve().parent / "output")
    args = ap.parse_args(argv)
    out = args.out
    (out / "artifacts").mkdir(parents=True, exist_ok=True)

    pred_doc = json.loads(PRED_PATH.read_text(encoding="utf-8"))
    comp = compose([EXP, TH], ids=["synthcol:synthetic-path-d-reco-counts", pred_doc["provenance"]["evidence_ids"][0]])
    resp = detector.response(CFG, 1.0, 0.0)  # in-bin weighting 1 + cos^2 theta, the predicted shape
    m = resp["matrix"]
    path_b_m = np.array(json.loads(PATH_B_RESULTS.read_text(encoding="utf-8"))["response"]["matrix"])
    resp_doc = json.loads(PATH_B_RESPONSE.read_text(encoding="utf-8"))

    pred_side = side_from_artifact(pred_doc)
    meas_side = {"artifact_type": "dataset-record", "observable": measurement_observable(), "status": ["synthetic"],
                 "uncertainties": [], "covariance": "absent", "corrections": []}
    p = plan(resp_doc["extension"]["includes"])
    g = gate(pred_side, meas_side, p["transformations"], p["mappings"], p["measurement_conditions"])
    if not g["comparable"]:
        (out / "gate_failure.json").write_text(json.dumps(g, indent=1) + "\n")
        print(json.dumps({"gate": "not comparable; dependent fit stopped", "mismatches": g["mismatches"]}, indent=1))
        return 1

    sigma_bins, fold_counts = folded(pred_doc, m)
    sigma_total = float(sigma_bins.sum())
    quad = quadrature_reference(sigma_total)
    fold_dev = float(np.max(np.abs(fold_counts / quad - 1)))
    r = float(pred_doc["extension"]["values"]["uncertainties"][0]["values"][0] / pred_doc["extension"]["values"]["values"][0])

    asimov = {}
    for mu_inj in (1.0, 1.25):
        fit = Model(mu_inj * fold_counts, fold_counts, LUMI_REL, r).fit()
        asimov[f"{mu_inj:g}"] = {"mu_hat": fit["mu_hat"], "interval_68": fit["interval_68"]}
    free = Model(fold_counts, fold_counts, LUMI_REL, r, constrain=False)
    q_free = 2.0 * (free.profiled(1.15)[0] - free.profiled(1.0)[0])

    rng = np.random.default_rng(args.seed)
    ev = generate_events.generate(CFG, int(rng.integers(2 ** 31)), sigma_pb=1.0 * sigma_total, a=1.0, b=0.0)
    lumi_obs = LUMI * (1.0 + LUMI_REL * rng.normal())
    counts = reco_counts(ev)
    obs_fit = Model(counts, fold_counts * lumi_obs / LUMI, LUMI_REL, r).fit()
    obs_pull = (obs_fit["mu_hat"] - 1.0) / (obs_fit["sigma_minus"] if obs_fit["mu_hat"] > 1 else obs_fit["sigma_plus"])
    toy_res = toys(fold_counts, sigma_total, r, args.toys, args.seed + 1)

    unfolded_side = side_from_artifact(json.loads((PLUGIN / "examples" / "collider-angular" / "output" / "artifacts" / "dataset_record.json").read_text(encoding="utf-8")))
    neg = []
    for v in negative_variants(pred_side, meas_side, p, unfolded_side):
        res = gate(v["prediction"], v["measurement"], v["transformations"], v["mappings"], v["conditions"])
        fields = [x["field"] for x in res["mismatches"]]
        neg.append({"name": v["name"], "expected_field": v["expect_field"], "rejected": not res["comparable"], "expected_field_reported": v["expect_field"] in fields,
                    "mismatches": [{k: x[k] for k in ("field", "reason", "resolve")} for x in res["mismatches"]]})
    conv = positive_conversion(pred_side, unfolded_side, p)

    docs, contract = artifacts(pred_doc, g, fold_counts, r, counts, obs_fit, toy_res, args.created)
    for name, doc in docs.items():
        (out / "artifacts" / f"{name}.json").write_text(json.dumps(doc, indent=1) + "\n")
    n_cov = args.toys
    cov_tol = CRITERIA["coverage_sigma"] * math.sqrt(0.6827 * 0.3173 / n_cov)
    passes = {
        "composition": comp["ok"],
        "gate_comparable": g["comparable"],
        "response_matches_path_b": bool(np.array_equal(m, path_b_m)),
        "fold_vs_quadrature": fold_dev < CRITERIA["fold_vs_quadrature_max_rel_dev"],
        "asimov_injection": all(abs(a["mu_hat"] - float(k)) < CRITERIA["asimov_mu_abs_dev"] for k, a in asimov.items()),
        "identifiable_only_with_constraint": q_free < 1e-6,
        "observed_consistent_with_injected": abs(obs_pull) < CRITERIA["observed_pull_abs"],
        "toy_pulls": all(abs(t["mean_pull"]) < CRITERIA["toy_mean_pull_abs"]
                         and CRITERIA["toy_pull_width"][0] < t["pull_width"] < CRITERIA["toy_pull_width"][1] for t in toy_res.values()),
        "toy_coverage": all(abs(t["coverage_68"] - 0.6827) < cov_tol for t in toy_res.values()),
        "negative_variants_rejected": all(n["rejected"] and n["expected_field_reported"] for n in neg),
        "documented_conversion_accepted": conv["comparable"],
        "contracts": all(c["ok"] for c in contract.values()),
    }
    trace = [{"artifact": d["artifact_id"], "type": d["artifact_type"], "inputs": [i["ref"] for i in d["inputs"]], "status": d["status"]}
             for d in docs.values()]
    results = {
        "label": "SYNTHETIC: data generated at mu = 1 from the illustrative synthetic-collider profile; not a physics result",
        "profiles_loaded": [EXP["id"], TH["id"]], "seed": args.seed, "toys": args.toys, "criteria": CRITERIA, "pass": passes,
        "composition": comp, "gate": {k: v for k, v in g.items() if k != "conventions"} | {"conventions": g["conventions"]},
        "sigma_pred_total_pb": sigma_total, "reference_rounding_rel": r,
        "folded_expectation": fold_counts.tolist(), "quadrature_reference": quad.tolist(), "fold_max_rel_dev": fold_dev,
        "asimov": asimov, "q_without_luminosity_constraint_at_mu_1.15": q_free,
        "observed_synthetic": {"n_generated": ev["meta"]["n_generated"], "reco_counts": counts.tolist(), "luminosity_measured_pb": lumi_obs,
                               "mu_hat": obs_fit["mu_hat"], "interval_68": obs_fit["interval_68"], "plateau_from_kappa": obs_fit["plateau"],
                               "pull_vs_injected": obs_pull},
        "toy_results": toy_res, "coverage_tolerance": cov_tol,
        "negative_variants": neg, "documented_conversion": {"comparable": conv["comparable"], "transformations": conv["transformations"]},
        "contract_trace": trace, "contract_validation": contract,
    }
    (out / "results.json").write_text(json.dumps(results, indent=1, default=float) + "\n")
    figures(counts, fold_counts, obs_fit, lumi_obs, out)
    write_report(out, results)
    digest = hashlib.sha256((out / "results.json").read_bytes()).hexdigest()
    print(json.dumps({"pass": passes, "results_sha256": digest}, indent=1))
    return 0 if all(passes.values()) else 1


def write_report(out: Path, r: dict) -> None:
    yes = lambda k: "pass" if r["pass"][k] else "FAIL"  # noqa: E731
    o = r["observed_synthetic"]
    lo, hi = o["interval_68"]
    lines = [
        "# Path D report: QED prediction vs synthetic reconstructed data (SYNTHETIC)",
        "",
        "**Status: synthetic.** The data come from the illustrative `experiment:synthetic-collider` generator with "
        "sigma_gen = mu x sigma_pred and mu = 1 injected; the harness passes sigma_pred from the Path C artifact to the generator. "
        "The fit therefore tests the comparison chain, not physics. No statement about new physics is made or possible.",
        "",
        f"Reproduce: `python3 examples/theory-comparison/run.py --toys {r['toys']} --seed {r['seed']}` (from the plugin root, "
        "after Paths B and C; D5 environment). Profiles loaded: " + ", ".join(f"`{p}`" for p in r["profiles_loaded"]) + ".",
        "",
        "## Contract trace",
        "",
        "Path C `prediction` → comparison gate (`comparison_spec.json`) → `folded_expectation.json` → `result.json` (mu fit). "
        "Every Path D artifact carries the `synthetic` status inherited from the data and the response.",
        "",
        "Gate transformations, in order: " + "; ".join(f"{t['kind']} (owner {t['owner']})" for t in r["gate"]["transformations"]) + ". "
        "Declared convention mapping: angle definitions equivalent (wording differs). Core convention keys stated only by the "
        "prediction (spin treatment, mass approximation) are reported as notes.",
        "",
        "## Pre-declared criteria and outcome",
        "",
        "| Check | Criterion | Result |", "|---|---|---|",
        f"| Composition of both profiles | namespaces disjoint, ids qualified | {yes('composition')} |",
        f"| Comparison gate | comparable after declared transformations | {yes('gate_comparable')} |",
        f"| Response | identical to the Path B response matrix | {yes('response_matches_path_b')} |",
        f"| Folded expectation vs independent quadrature | max relative deviation < {r['criteria']['fold_vs_quadrature_max_rel_dev']} | {yes('fold_vs_quadrature')} ({r['fold_max_rel_dev']:.1e}) |",
        f"| Asimov injection at mu = 1 and 1.25 | abs(mu_hat - mu) < {r['criteria']['asimov_mu_abs_dev']} | {yes('asimov_injection')} |",
        f"| Identifiability | without the luminosity constraint q(1.15) ≈ 0 (mu x L is what the counts fix) | {yes('identifiable_only_with_constraint')} |",
        f"| Synthetic sample at mu = 1 | abs(pull) < {r['criteria']['observed_pull_abs']} | {yes('observed_consistent_with_injected')} |",
        f"| Toys at mu = 1 and 0.8 | mean pull abs < 0.2, width in (0.85, 1.15) | {yes('toy_pulls')} |",
        f"| 68% interval coverage | within 3 binomial sigma ({r['coverage_tolerance']:.3f}) of 0.683 | {yes('toy_coverage')} |",
        f"| Mismatched variants | each rejected, naming the field | {yes('negative_variants_rejected')} |",
        f"| Documented conversion (T08) | fiducial restriction + level identification accepted | {yes('documented_conversion_accepted')} |",
        f"| Contract artifacts | all valid with both profile vocabularies | {yes('contracts')} |",
        "",
        "## Result on the synthetic sample",
        "",
        f"sigma_pred = {r['sigma_pred_total_pb']:.1f} pb (Path C). {o['n_generated']} events generated; measured luminosity "
        f"{o['luminosity_measured_pb']:.3f} pb^-1 (synthetic auxiliary measurement). mu_hat = {o['mu_hat']:.4f}, 68% interval "
        f"[{lo:.4f}, {hi:.4f}], pull against the injected value {o['pull_vs_injected']:.2f}. The bounded rounding nuisance makes mu_hat "
        f"a plateau [{o['plateau_from_kappa'][0]:.4f}, {o['plateau_from_kappa'][1]:.4f}].",
        "",
        "| Injected mu | toys | mean pull | pull width | 68% coverage |", "|---|---|---|---|---|",
    ]
    for k, t in r["toy_results"].items():
        lines.append(f"| {k} | {t['toys']} | {t['mean_pull']} | {t['pull_width']} | {t['coverage_68']} |")
    lines += ["", "## Rejected variants", "", "| Variant | Rejected | Reported field and reason |", "|---|---|---|"]
    for n in r["negative_variants"]:
        hit = [x for x in n["mismatches"] if x["field"] == n["expected_field"]]
        first = (hit or n["mismatches"] or [{"field": "-", "reason": "-"}])[0]
        lines.append(f"| {n['name']} | {'yes' if n['rejected'] else 'NO'} | `{first['field']}`: {first['reason']} |")
    lines += ["", "## Limitations", "",
              "- Truncation (higher orders, Z exchange) is not quantified, so mu is conditional on the tree-level prediction.",
              "- The response uses the predicted shape inside each bin; a different shape hypothesis needs its own response.",
              "- The data are synthetic and generated from the same shape, so agreement is expected by construction.",
              "", "Figure: `folded_comparison.png`. Artifacts: `artifacts/*.json`.", ""]
    (out / "report.md").write_text("\n".join(lines))


if __name__ == "__main__":
    sys.exit(main())
