#!/usr/bin/env python3
"""Render a systematics registry CSV as a booktabs LaTeX table for a paper or note.

Input: a CSV in the format of <plugin root>/skills/hep-analysis/assets/systematics.csv (source, type, process_scope,
era_scope, region_scope, correlation_key, rate_shape, payload, validation), optionally with impact columns of your
own (for example `impact_percent`) and a per-row `status` column. Every table carries a status label: give --status
(synthetic, observed, preliminary, ...) for the whole table, or a `status` column for every row; a table without one is
refused, so unlabeled numbers never reach a manuscript. A synthetic or preliminary label appears in the caption and in a
LaTeX comment; per-row statuses get their own column.

Usage:
  python3 systematics_table_tex.py --input systematics.csv --status synthetic [--columns source,type,correlation_key]
         [--caption TEXT] [--label tab:systematics] [--out table.tex]
Needs \\usepackage{booktabs} in the document. Exit codes: 0 written, 2 refused input. Standard library only.
"""
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

DEFAULT_COLUMNS = ["source", "type", "process_scope", "region_scope", "correlation_key", "rate_shape"]
HEADERS = {"source": "Source", "type": "Type", "process_scope": "Processes", "era_scope": "Periods",
           "region_scope": "Regions", "correlation_key": "Correlation", "rate_shape": "Effect", "payload": "Payload",
           "validation": "Validation", "status": "Status"}
STATUSES = ("synthetic", "asimov", "observed", "preliminary", "published", "unvalidated", "user-supplied")
FLAGGED = ("synthetic", "asimov", "preliminary", "unvalidated")  # said in the caption itself
SPECIAL = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_", "{": r"\{",
           "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}


class Refused(ValueError):
    """Input the table cannot be written from."""


def tex(text: str) -> str:
    return "".join(SPECIAL.get(c, c) for c in text)


def render(rows: list[dict], columns: list[str], status: str | None, caption: str, label: str) -> str:
    if not rows:
        raise Refused("the CSV has no rows")
    row_status = "status" in rows[0]
    if status is None and not row_status:
        raise Refused("no status: give --status (for example synthetic or observed) or a status column")
    statuses = {status} if status else set()
    if row_status:
        for i, r in enumerate(rows, 1):
            s = (r.get("status") or "").strip()
            if s not in STATUSES:
                raise Refused(f"row {i}: status {s!r} is not one of {', '.join(STATUSES)}")
            statuses.add(s)
    missing = [c for c in columns if c not in rows[0]]
    if missing:
        raise Refused(f"columns not in the CSV: {missing}")
    if row_status and "status" not in columns:
        columns = columns + ["status"]
    flagged = sorted(s for s in statuses if s in FLAGGED)
    head = " & ".join(HEADERS.get(c, tex(c.replace("_", " ").capitalize())) for c in columns)
    body = [" & ".join(tex((r.get(c) or "").strip()) for c in columns) + r" \\" for r in rows]
    full_caption = caption
    if flagged:
        full_caption = f"{' and '.join(s.upper() for s in flagged)}: {caption}"
    lines = [f"% generated by systematics_table_tex.py; status: {', '.join(sorted(statuses))}",
             r"\begin{table}[htbp]", r"\centering", f"\\caption{{{tex(full_caption)}}}", f"\\label{{{label}}}",
             f"\\begin{{tabular}}{{{'l' * len(columns)}}}", r"\toprule", head + r" \\", r"\midrule", *body,
             r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--input", type=Path, required=True, help="systematics CSV (assets/systematics.csv format)")
    ap.add_argument("--status", choices=STATUSES, help="status of the whole table (or give a status column)")
    ap.add_argument("--columns", default=",".join(DEFAULT_COLUMNS), help="comma-separated CSV columns, in order")
    ap.add_argument("--caption", default="Sources of systematic uncertainty and how they are correlated.")
    ap.add_argument("--label", default="tab:systematics")
    ap.add_argument("--out", type=Path, help="write here instead of standard output")
    args = ap.parse_args(argv)
    try:
        with args.input.open(newline="", encoding="utf-8") as fh:
            rows = list(csv.DictReader(fh))
        text = render(rows, [c.strip() for c in args.columns.split(",") if c.strip()], args.status, args.caption, args.label)
    except (OSError, Refused, csv.Error) as exc:
        print(f"systematics_table_tex.py: error: {exc}", file=sys.stderr)
        return 2
    if args.out:
        args.out.write_text(text, encoding="utf-8")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
